version: '3.8'

services:
  app:
    build: .
    container_name: rest_api_calculation_penalty
    restart: always
    environment:
      SPRING_APPLICATION_NAME: rest_api_calculation_penalty
      SPRING_DATASOURCE_URL: jdbc:postgresql://95.31.250.137:5432/projekt2
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8082:8082"  # Приводим порты в соответствие с Dockerfile
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: projekt2
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
